### PR TITLE
Fixed for v1 Heroku add-on provider API

### PR DESCRIPTION
**Pull request by djcp**
The v2 provider API is being deprecated and these fixes should allow new
add-ons to work against the v1 API without incident.  There's some odd internal special casing in how add-on set config vars work that make me concerned this might end up with `SECUREKEY` (because "securekey" is  the add-on slug) but it may be fine.  My plan was to roll this out, do an immediate add-on creation, check the var and then rollback if needed.

### CODE REVIEW

**Comment by mathias** [comment]
Hi @will , can you take a look at this? We need you to move off the V2 Provider API.

**Comment by will** [comment]
@mathias yeah I can take a look at this. I'm not clear does this also need to update the addon-manifest at the same time?

**Comment by mathias** [comment]
Yes, please see https://devcenter.heroku.com/articles/add-on-manifest#api-version for setting it to version 1 in your manifest.

**Comment by will** [comment]
I'm also worried that going back to the V1 API will break all of my callback urls, they all look like `https://api.heroku.com/vendor/resources/<digits>` and all the app/resource ids I have look like `resource<digits>@heroku.com`.  If these change, all the rotations will break.

```
=> select distinct regexp_replace(callback_url, '\d+', '?') as callback_url, regexp_replace(heroku_id, '\d+', '?') as heroku_id from users where created_at > '2012-09-01' ;
               callback_url                |      heroku_id
-------------------------------------------+----------------------
 https://api.heroku.com/vendor/resources/? | resource?@heroku.com
(1 row)
```

**Comment by mathias** [comment]
You're right. And part of getting add-ons off V2 is to get rid of those inconsistencies. Let me get back to you.

**Comment by mathias** [comment]
We may need to work with you to give you a CSV of Resource ID -> "HID" (app123@heroku.com). Alternatively, if you think you'd be willing to upgrade to V3 (Which will change some responses but for provisioning is very similar) you could use the resource.uuid that is already in the serialized V2 responses and upgrade to use V3 (which uses the resource.uuid as a primary key.) This would likely mean you'd need to loop over all your records, hitting the callback URL for each add-on, and saving off the resource.uuid for later use. Let me know if this approach for V3 would work for you. We've got it documented here: https://devcenter.heroku.com/articles/migrating-to-v3-of-the-add-on-partner-api but it is written from a v1 -> v3 perspective, as no one should be on v2.

**Comment by mathias** [comment]
And I should note, for Securekey's use case, you can probably safely ignore the async provisioning and Unified API aspects and just return immediate success responses to provisioning as before.

**Comment by will** [comment]
I don’t think the HIDs will work, since you can attach securekey multiple times to the same app, and HIDs wont be unique in that case. 

To go to the V3, it looks like I'm going to also have to get oauth thingamajigs in addition to the UUIDs?

**Comment by will** [comment]
https://devcenter.heroku.com/articles/platform-api-for-partners#exchanging-the-grant-code 
wait you cant get the real token during provisioning, you have to respond first then make calls afterwards to get the long lived token? I guess I could start a thread and sleep for a bit then try and get all that. Seems sketchy though, I have to respond that it's okay before I know if I can actually change config vars in the future. Like if I respond ok, then there's an outage.

**Comment by mathias** [comment]
The integration should still work if you respond success to the provision request and don't exchange the token. The token is only needed for hitting these endpoints: https://devcenter.heroku.com/articles/platform-api-for-partners#list-of-standard-platform-api-endpoints

For Securekey's use, I think you only need this, which still exists and can be used in V3: https://devcenter.heroku.com/articles/add-on-app-info#update-config-vars

**Comment by will** [comment]
I'm trying with a staging version of the addon, and it seems to be upset with the config var name

```
~/c/securekey (master)> curl -H 'Accept: application/vnd.heroku+json; version=1'  https://securekey-staging:$PASS@api.heroku.com/vendor/apps/b3e2d82b-4dc3-4246-9a44-db1e80ef0d80
{
  "callback_url":"https://api.heroku.com/vendor/apps/b3e2d82b-4dc3-4246-9a44-db1e80ef0d80",
  "config":{
    "KEY":"8EFD6857A8BF9B80E04C8677EB68F8C3111ED3AB9350DD2D1C0BA221C3A46571,459E9900375B12DF3C5358ED6664B678DAF17973ACDF1025EC9E5591450DB4C1",
    "SECUREKEY_STAGING_GOLD_KEY":"8EFD6857A8BF9B80E04C8677EB68F8C3111ED3AB9350DD2D1C0BA221C3A46571,459E9900375B12DF3C5358ED6664B678DAF17973ACDF1025EC9E5591450DB4C1"
  },
...
}
~/c/securekey (master)> curl -H 'Accept: application/vnd.heroku+json; version=1'  https://securekey-staging:$PASS@api.heroku.com/vendor/apps/b3e2d82b-4dc3-4246-9a44-db1e80ef0d80 -X PUT -d '{"config":{"KEY":"a,b"}}'
{
  "id":"forbidden",
  "message":"You may only update config vars defined in your manifest."
}
```
The manifest is mostly the same as the current prod version. I kept the version 2 to see what the migration would be like.
```
{
  "id": "securekey-staging",
  "api": {
    "regions": [
      "us",
      "eu"
    ],
    "sso_url": null,
    "password": <redact>",
    "sso_salt": null,
    "production": {
      "base_url": "https://securekey-staging.herokuapp.com/"
    },
    "default_config_var": "SECURE_KEY"
  },
  "$base": <redact?>,
  "api_url": {
    "base_url": "https://securekey-staging.herokuapp.com/"
  },
  "version": 2,
  "requires": [
    "attachable",
    "many_per_app"
  ]

```

**Comment by will** [comment]
I've backfilled all the uuids, but still need a way to use the new endpoint to set the env vars that will work when using the uuids

**Comment by mathias** [comment]
Hi @will,

I'm quite certain you can use the resource UUID in this request in V1: 

PUT https://{username}:{password}@api.heroku.com/vendor/apps/{id}

https://devcenter.heroku.com/articles/add-on-app-info#update-config-vars

That endpoint may also still work just fine when your add-on is technically on V2. I've never tried it, since we don't run any V2 test/debugging add-ons.

**Comment by will** [comment]
It works in so far as it returns data, but when I try to set a config var, it says it's not defined in my manifest

```
~/c/securekey (master)> curl -H 'Accept: application/vnd.heroku+json; version=1'  https://securekey-staging:$PASS@api.heroku.com/vendor/apps/b3e2d82b-4dc3-4246-9a44-db1e80ef0d80
{
  "callback_url":"https://api.heroku.com/vendor/apps/b3e2d82b-4dc3-4246-9a44-db1e80ef0d80",
  "config":{
    "KEY":"8EFD6857A8BF9B80E04C8677EB68F8C3111ED3AB9350DD2D1C0BA221C3A46571,459E9900375B12DF3C5358ED6664B678DAF17973ACDF1025EC9E5591450DB4C1",
    "SECUREKEY_STAGING_GOLD_KEY":"8EFD6857A8BF9B80E04C8677EB68F8C3111ED3AB9350DD2D1C0BA221C3A46571,459E9900375B12DF3C5358ED6664B678DAF17973ACDF1025EC9E5591450DB4C1"
  },
...
}
~/c/securekey (master)> curl -H 'Accept: application/vnd.heroku+json; version=1'  https://securekey-staging:$PASS@api.heroku.com/vendor/apps/b3e2d82b-4dc3-4246-9a44-db1e80ef0d80 -X PUT -d '{"config":{"KEY":"a,b"}}'
{
  "id":"forbidden",
  "message":"You may only update config vars defined in your manifest."
}
```

**Comment by mathias** [comment]
`KEY` and `SECURE_STAGING_GOLD_KEY` look wrong there if your manifest sets `"default_config_var": "SECURE_KEY"`. I think we make it so that you don't have to know the attachment name (And could have many attachment names) and `GOLD` there looks like an attachment name, to me.

Can you try the same curl but only `SECURE_KEY` as the key? I am fairly certain it expands that out to all the attachment names, you don't have to know them in your code. (Add-on partners typically aren't even aware of attachments unless they're using add-on webhooks.)

**Comment by mathias** [comment]
Also, now that I'm looking at it, I am fairly certain that `default_config_var` is not used anymore and is possibly getting ignored. The [Addon manifest doc](https://devcenter.heroku.com/articles/add-on-manifest) lists ```  "api": {
    "config_vars_prefix": "ERRORBUCKET",
    "config_vars": [
      "ERRORBUCKET_URL"
    ],```

So you may have to push a manifest that sets `"config_var_prefix": "SECURE_KEY"` instead.

**Pull request closed without merging**
